# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: 'Blogger'
    org_name: ''
    description: 'Giving tips to virtual assistants & freelancers, reviewing websites and AI tools and talking about Web3 technologies.'
    twitter: 'ThatVirtualG'
  analytics:
    google_analytics: 'G-YZ2H790WQD'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: 'cWAuTpUW-3M23PpXnfvjbu5Htp9czA5FY4l4ErwIX50'
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: 'Â© {year} That Virtual Guy. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '15:04'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/HugoBlox/hugo-blox-builder/'
    content_dir: starters/blog/content
    branch: main
